Today the build and deploy scripts have made a leap forward.
The next step is to add a configuration file in etc for these thus making customization easier.

diff --git a/bin/build b/bin/build
--- a/bin/build
+++ b/bin/build
@@ -2,7 +2,9 @@
 
 CMD="rsync --stats -avzrp"
 OWD=`pwd`
-DESTBASE=wproot/wordpress/wp-content/
+SRC=${OWD}/src
+DESTBASE=wproot/wordpress/wp-content
+SILENT=/dev/null 2>&1
 
 # Deploy to environment: 'production' or 'staging'
 TARGET=$1
@@ -11,43 +13,106 @@ TARGET=$1
 # Setup deployment destination
 # TODO: change this to local by default and add a true help option
 if [ -z "$1" ]; then
-	#echo "Usage: $0 [production|staging|local]"
-	#exit 1
 	TARGET=local
 fi
+
+####
+# TODO: add a getopt process to pull out command line switches like -h
+#
+function helpMsg() {
+	echo "Usage: $0 [production|preprod|staging|local]"
+	exit 1
+}
 
 # Do a local deploy if SETUP_DBDUMP or SETUP_DBDUMP
 if [ ! -z "$SETUP_DBDUMP" -o ! -z "$SETUP_DBDUMP_PATH" ]; then
 	TARGET=local
 fi
 
-####
-# Because even in BASH we should build reusable entities
+function getRevision() {
+    git rev-parse --short HEAD > wproot/revision
+}
+
+function getComposerManifest() {
+    if [ ! -e composer.json ]
+    then
+        ln -s ../../composer.json
+    fi
+}
+
+#####
+# SymLink the dev system vendors into the destination; this reduces the need to reinstall each build.
 #
+function getVendors() {
+    if [ ! -e vendor ]
+    then
+        ln -s ../../vendor
+    fi
+}
+
+#####
+# At the time of this development something has gone awry with
+# the composer auto-installer. This is a suitable backup.
+#
+function installWordPressCore() {
+    if [ -e vendor/johnpbloch/wordpress-core/ ]
+    then
+        if [ ! -e wproot/wordpress ]
+        then
+            mkdir -p wproot/wordpress
+        fi
+        ${CMD} vendor/johnpbloch/wordpress-core/ wproot/wordpress/
+    fi
+}
+
+####
+# Install/update as necessary any package changes FIRST
+#
+function preBuild() {
+    composer update
+}
+
+####
+# Install the config files as necessary
+# TODO: change this to symlinks on local builds and persist the copy for deployment builds
+#
+function installConfigs() {
+    cp ${OWD}/etc/*-conf.php wproot/
+}
+
+####
+# Because even in BASH we should build reusable blocks
+#
+# This searches for source files in the appropriate entity
+# spaces and SymLink them into the local dev build
 #
 function linkAssets() {
-    ENTITY=${1}
-    DEST=${DESTBASE}${ENTITY}/
-    pushd ${DEST}
+    ENTITY=${1} # mu-plugins, plugins, themes
+    DEST=${DESTBASE}/${ENTITY}/
+    pushd ${DEST} > ${SILENT}
 
-    if [ -e ${OWD}/${ENTITY} ]
+    # Search the source for the entity
+    if [ -e ${SRC}/${ENTITY} ]
     then
-        echo "${ENTITY} exists, searching for mu-plugin assets"
-        for ASSET in ${OWD}/${ENTITY}/*
+        #echo "The ${ENTITY} destination exists."
+        for ASSET in ${SRC}/${ENTITY}/*
         do
-            echo ${ASSET##*/}
+            #echo "Searching for source matching assets in ${ENTITY}."
+            # echo ${ASSET##*/}
             if [ ! -e ${ASSET##*/} ]
             then
-                echo "Missing ${ENTITY} assets found attempting to symlink them."
+                #echo "Missing ${ASSET##*/} asset, attempting to symlink from ${SRC}/${ENTITY}/${ASSET##*/}."
+                #echo ${SRC}/${ENTITY}/${ASSET}
                 #echo ${ASSET}
                 #echo -n "Current working directory is "
                 #pwd
+                #ln -s ${SRC}/${ENTITY}/${ASSET}
                 ln -s ${ASSET}
-                #popd
+                #popd > ${SILENT}
             fi
         done
     fi
-    popd
+    popd > ${SILENT}
 }
 
 
@@ -60,72 +125,99 @@ function localBuild() {
     ####
     # Check for items in mu-plugins and symlink the ones that don't
     # already exist into the destination
+    installWordPressCore
     linkAssets 'mu-plugins'
     linkAssets 'plugins'
     linkAssets 'themes'
 }
 
-function preDeployBuild() {
 ####
-# This section needs work but as a first pass it will suffice
-# TODO: change the following to symlink on local builds and cp for all deployment builds
-# This change will require new functions that search the source path(s) and symlink the
-# top level items into the destinations the symlink operation(s) should be indempotent
-# thus we may need to check the existence of the target in the destination directory.
+# Simple hack to make WordPress uploads work in the vagrant.
+# This is for local dev ONLY!
 #
-# The plan is to pass in a deployment destination target on the command line and build
-# a hard copy read for shipping to that end point.
-
-# Check for local mu-plugins
-if [ -e mu-plugins ]
-then
-    ${CMD} mu-plugins/ wproot/wordpress/wp-content/mu-plugins/
-fi
-
-# Check for local plugins
-if [ -e plugins ]
-then
-    ${CMD} plugins/ wproot/wordpress/wp-content/plugins/
-fi
-
-# Check for local themes
-if [ -e themes ]
-then
-${CMD} themes/ wproot/wordpress/wp-content/themes/
-fi
+function createUploads() {
+    if [ ! -e ${DESTBASE}/uploads ]
+    then
+        mkdir ${DESTBASE}/uploads
+        chmod -R 777 ${DESTBASE}/uploads
+    fi
 }
 
 ####
+# This symlinks parts of the build composer manifest and vendor directory that would
+# result in unnecessary duplication or even possible build discrepancies. Thus installing
+# from vendor cache.
+#
+# There's just no viable reason to reinstall everything that should already
+# be in the dev tree.
+function preDeployBuild() {
+    ENTITY=${1}
+    DEST='work/'${ENTITY}/
+    mkdir -p ${DEST}
+    pushd ${DEST} > ${SILENT}
+
+    getComposerManifest
+    getVendors
+    installWordPressCore
+
+    ####
+    # This will look st the manifest and vendor tree see symlinking above
+    preBuild
+
+    installConfigs
+
+    getRevision
+
+    popd > ${SILENT}
+
+    # Check for local mu-plugins
+    if [ -e ${SRC}/mu-plugins ]
+    then
+        ${CMD} ${SRC}/mu-plugins/ ${DEST}${DESTBASE}/mu-plugins/
+    fi
+
+    # Check for local plugins
+    if [ -e ${SRC}/plugins ]
+    then
+        ${CMD} ${SRC}/plugins/ ${DEST}${DESTBASE}/plugins/
+    fi
+
+    # Check for local themes
+    if [ -e ${SRC}/themes ]
+    then
+        ${CMD} ${SRC}/themes/ ${DEST}${DESTBASE}/themes/
+    fi
+}
+
+####
+# Update the mu-plugins, plugins and themes as necessary
+# Some of this actually could be move into the deploy script
 # TODO: change targets to work/TARGET/wproot/...
 #
 case "$TARGET" in
 	local)
+	    preBuild
+	    installConfigs
+        getRevision
 		localBuild
+		createUploads
 		exit 0
 		;;
 	production)
-		url=git@git.wpengine.com:production/rdigest.git
+		preDeployBuild production
+
+		GITURL=git@git.wpengine.com:production/somesite.git
 		;;
 	preprod)
-		url=git@git.wpengine.com:staging/rdigest.git
+	    preDeployBuild preprod
+		GITURL=git@git.wpengine.com:staging/somesite.git
 		;;
 	staging)
-		url=git@git.wpengine.com:production/readersdigest.git
+	    preDeployBuild staging
+		GITURL=git@git.wpengine.com:production/somesite.git
 		;;
 	*)
 		echo "Invalid environment: '$env'. Must be 'production', 'preprod', 'staging' or 'local'"
 		exit 1
 		;;
 esac
-
-####
-# Install/update as necessary any package changes
-#
-composer update
-
-####
-# Install the config files as necessary
-# TODO: change this to symlinks on local builds and persist the copy for deployment builds
-#
-cp etc/*-conf.php wproot/
-
diff --git a/bin/deploy b/bin/deploy
--- a/bin/deploy
+++ b/bin/deploy
@@ -1,5 +1,8 @@
 #!/usr/bin/env bash
 
+EXCLUSIONS="--exclude='.git*' --exclude='.svn*'"
+SILENT=/dev/null 2>&1
+
 ####
 # Deployment is dependent up the appropriate destination being
 # properly configured in the .ssh/config. This eliminates the
@@ -11,4 +14,81 @@
 #
 # TODO Make the deployment drive a build for the appropriate destination environment
 #
-rsync --stats -avzrp wproot mikel@ra2:/web/test/
+
+####
+# Setup deployment destination
+# TODO: change this to local by default and add a true help option
+if [ -z "$1" ]; then
+	TARGET=local
+else
+    TARGET=$1
+fi
+
+####
+# TODO: add a getopt process to pull out command line switches like -h
+#
+function helpMsg() {
+	echo "Usage: $0 [production|preprod|staging|local]"
+	exit 1
+}
+
+function verifyEntity() {
+    ENTITY=${1}
+    if [ ! -e work/${ENTITY} ]
+    then
+        echo
+        echo "The '${ENTITY}' target was not found."
+        echo "Suggest trying to execute 'build ${ENTITY}' first."
+        echo
+        exit 1
+    fi
+}
+
+function deployToProd() {
+    pushd work/production > ${SILENT}
+    rsync ${EXCLUSIONS} --stats -avzCrp wproot mikel@ra2:/web/olivent_network/
+    popd > ${SILENT}
+}
+
+function deployToPreProd() {
+    pushd work/production > ${SILENT}
+    rsync ${EXCLUSIONS} --stats -avzCrp wproot mikel@ra2:/web/test/
+    popd > ${SILENT}
+}
+
+function deployToStag() {
+    pushd work/production > ${SILENT}
+    rsync ${EXCLUSIONS} --stats -avzCrp wproot mikel@ra2:/web/staging/
+    popd > ${SILENT}
+}
+
+####
+# Update the mu-plugins, plugins and themes as necessary
+#
+# TODO: change targets to be dynamic
+#
+case "$TARGET" in
+	local)
+	    verifyEntity ${TARGET}
+		exit 0
+		;;
+	production)
+		verifyEntity ${TARGET}
+		deployToProd
+		GITURL=git@git.wpengine.com:production/somesite.git
+		;;
+	preprod)
+	    verifyEntity ${TARGET}
+	    deployToPreProd
+		GITURL=git@git.wpengine.com:staging/somesite.git
+		;;
+	staging)
+	    verifyEntity ${TARGET}
+	    deployToStag
+		GITURL=git@git.wpengine.com:production/somesite.git
+		;;
+	*)
+		echo "Invalid environment: '$env'. Must be 'production', 'preprod', 'staging' or 'local'"
+		exit 1
+		;;
+esac
